image: maven:3.8.4-jdk-11

variables:
  QT_VERSION: "6.7.1"
  QT_INSTALL_DIR: "/opt/Qt"
  JAVA_HOME: "/usr/lib/jvm/java-11-openjdk"

stages:
  - setup
  - build
  - test

before_script:
  # Update package list and install dependencies
  - apt-get update && apt-get install -y wget unzip gcc g++ make
  # Install Qt
  - wget https://www.qt.io/download-qt-installer-oss -O qt-installer.run
  - chmod +x qt-installer.run
  - ./qt-installer.run --script qt-noninteractive.qs
  - export PATH="${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64/bin:$PATH"
  - export QT_QPA_PLATFORM_PLUGIN_PATH="${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64/plugins/platforms"
  - echo $PATH
  - echo $QT_QPA_PLATFORM_PLUGIN_PATH
  # Download and set up QtJambi
  - wget https://github.com/qtjambi/qtjambi/releases/download/v6.7.1/qtjambi-linux-x64-6.7.1.zip
  - unzip qtjambi-linux-x64-6.7.1.zip -d /opt/qtjambi
  - export QTJAMBI_LIBS="/opt/qtjambi/native"
  - export LD_LIBRARY_PATH="${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64/lib:${QTJAMBI_LIBS}:$LD_LIBRARY_PATH"
  - echo $LD_LIBRARY_PATH

setup:
  stage: setup
  script:
    - echo "Setting up environment"

build:
  stage: build
  script:
    # Compile the Java project
    - mvn clean compile
    # Package the project
    - mvn package

test:
  stage: test
  script:
    # Run the Java application
    - java -Djava.library.path=$QTJAMBI_LIBS -jar target/your-java-app.jar

#artifacts:
 # paths:
  #  - target/*.jar
