image: python:latest

stages:         
  - build

build-job:      
  stage: build
  script:
    - echo "Compiling the code..."
    - python --version
    - pip install --upgrade pip
    - pip install PyQt5
    - python main.py test
    - echo "Compile complete."
