image: python:latest

stages:         
  - build
  - test

build-job:      
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test-job:  
  stage: test  
  script:
    - echo "Running unit tests...
    - python .\URLUtilsTest.py
    - echo "Code coverage is 100%"
