image: darkmattercoder/qt-build:5.13.0
# entrypoint: [""]


stages:
   - Build
   - Run
   

before_script:
#   - apt-get update && apt -y install make autoconf
#   - sudo apt-get update -q -y
#   - apt-get --yes install libqt5location5 
# this does not work 


Build code:
   stage: Build
   script:
      - apt update && apt -y install make autoconf
      - qmake src/FineDustMap/FineDustMap.pro -spec linux-g++
      - make

#  artifacts:
#    paths:
#      - mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before

Run:
   stage: Run
   script:
      - ls
      - cd src/
      - ls 
      - cd FineDustMap/
      - ls 
      - ./FineDustMap
