image: python:latest

stages:         
  - build
  - test

build-job:      
  stage: build
  script:
    - echo "Compiling the code..."
    - python --version
    - pip install --upgrade pip
    - pip install PyQt5
    - python main.py test
    - echo "Compile complete."

test-job:  
  stage: test  
  script:
    - echo "Running unit tests..."
    - python ./URLUtilsTest.py
    - echo "All tests passed."
